### ISSUE TITLE
zabbix java gateway not properly reading in properties

### ISSUE THREAD

**Issue by dberardo-com** [zabbix/zabbix-docker#1576]
i am starting the java gaeway container with this env:

- name: JAVA_OPTIONS
   value: "-Dcom.sun.management.jmxremote.authenticate=false  -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.registry.ssl=false"

as i want to connect it to a remote endpoint without auth and  without SSL.

this props are correctly passed to the java --server command (verified with ps aux) but i still get this error in console:

```
2024-11-29 12:18:24.999 [pool-2-thread-4] DEBUG com.zabbix.gateway.SocketProcessor - error caused by
java.io.EOFException: null
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
	at com.zabbix.gateway.BinaryProtocolSpeaker.getRequest(BinaryProtocolSpeaker.java:51)
	at com.zabbix.gateway.SocketProcessor.run(SocketProcessor.java:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-29 12:18:24.999 [pool-2-thread-4] DEBUG c.z.gateway.BinaryProtocolSpeaker - sending the following data in response: {"response":"failed"}
2024-11-29 12:18:25.000 [pool-2-thread-2] DEBUG com.zabbix.gateway.SocketProcessor - finished processing incoming connection
2024-11-29 12:18:25.000 [pool-2-thread-4] DEBUG com.zabbix.gateway.SocketProcessor - finished processing incoming connection
2024-11-29 12:18:26.593 [pool-2-thread-5] DEBUG c.z.g.ZabbixJMXConnectorFactory - connecting to JMX agent at 'service:jmx:rmi:///jndi/rmi://<host and port>/jmxrmi'
2024-11-29 12:18:26.998 [pool-2-thread-5] WARN  com.zabbix.gateway.SocketProcessor - error processing request, item "jmx["kafka.controller:type=KafkaController,name=ReplicasToDeleteCount","Value"]" failed: SSL peer shut down incorrectly: service:jmx:rmi:///jndi/rmi://<host and port>/jmxrmi
2024-11-29 12:18:26.999 [pool-2-thread-5] DEBUG com.zabbix.gateway.SocketProcessor - error caused by
com.zabbix.gateway.ZabbixException: SSL peer shut down incorrectly: service:jmx:rmi:///jndi/rmi://<host and port>/jmxrmi
	at com.zabbix.gateway.JMXItemChecker.getValues(JMXItemChecker.java:168)
	at com.zabbix.gateway.SocketProcessor.run(SocketProcessor.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-11-29 12:18:26.999 [pool-2-thread-5] DEBUG c.z.gateway.BinaryProtocolSpeaker - sending the following data in response: {"response":"failed","error":"SSL peer shut down incorrectly: service:jmx:rmi:\/\/\/jndi\/rmi:\/\/<host and port>\/jmxrmi"}
```

therefore i am assuming that SSL is still being tried? "SSL peer shut down incorrectly"

**Comment by dotneft** [comment]
I would like to draw your attention to the fact that this issue tracker is for Zabbix docker images defects only.

Please use https://www.zabbix.com/community for community support, https://support.zabbix.com/servicedesk for commercial support or contact our Sales team for commercial support options.

**Comment by dberardo-com** [comment]
Thanks for the disclaimer, I wanted to go sure first that it was not a problem related only to the docker distribution of the java gateway. I assume it is not then
